### ISSUE TITLE
No longer work with SONOS 9.1 update :-(

### ISSUE THREAD

**Issue by roe1974** [jens-maus/hm-sonos#4]
ich habe heute das update von SONOS durchgeführt auf 9.1
leider habe ich dann irrtümlich in deinem add-on einen UDP scan durchgeführt....
er findet jetzt leider keine SONOS boxen mehr ... ist ein problem von 9.1 :(
kannst Du das fixen ??

lg Richard

PS: vor dem rescan hat alles funktioniert.....kann man die SONOS irgendwo "reincodieren" ??

lg

**Comment by fiveyears** [comment]
There is no problem with me, Topology works great, no change is needed

**Comment by roe1974** [comment]
did you trie the button "rescan zoneplayers over UDP" ????
